/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWithdrawalsRouteImport } from './routes/_authenticated.withdrawals'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated.support'
import { Route as AuthenticatedReferralsRouteImport } from './routes/_authenticated.referrals'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as ApiPublicPayheroWithdrawCallbackRouteImport } from './routes/api/public/payhero/withdraw-callback'
import { Route as ApiPublicPayheroCallbackRouteImport } from './routes/api/public/payhero/callback'
import { Route as ApiPublicHooksResolveBinaryTradesRouteImport } from './routes/api/public/hooks/resolve-binary-trades'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWithdrawalsRoute =
  AuthenticatedWithdrawalsRouteImport.update({
    id: '/withdrawals',
    path: '/withdrawals',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReferralsRoute = AuthenticatedReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicPayheroWithdrawCallbackRoute =
  ApiPublicPayheroWithdrawCallbackRouteImport.update({
    id: '/api/public/payhero/withdraw-callback',
    path: '/api/public/payhero/withdraw-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPayheroCallbackRoute =
  ApiPublicPayheroCallbackRouteImport.update({
    id: '/api/public/payhero/callback',
    path: '/api/public/payhero/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksResolveBinaryTradesRoute =
  ApiPublicHooksResolveBinaryTradesRouteImport.update({
    id: '/api/public/hooks/resolve-binary-trades',
    path: '/api/public/hooks/resolve-binary-trades',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/withdrawals': typeof AuthenticatedWithdrawalsRoute
  '/api/public/hooks/resolve-binary-trades': typeof ApiPublicHooksResolveBinaryTradesRoute
  '/api/public/payhero/callback': typeof ApiPublicPayheroCallbackRoute
  '/api/public/payhero/withdraw-callback': typeof ApiPublicPayheroWithdrawCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/withdrawals': typeof AuthenticatedWithdrawalsRoute
  '/api/public/hooks/resolve-binary-trades': typeof ApiPublicHooksResolveBinaryTradesRoute
  '/api/public/payhero/callback': typeof ApiPublicPayheroCallbackRoute
  '/api/public/payhero/withdraw-callback': typeof ApiPublicPayheroWithdrawCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/referrals': typeof AuthenticatedReferralsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/withdrawals': typeof AuthenticatedWithdrawalsRoute
  '/api/public/hooks/resolve-binary-trades': typeof ApiPublicHooksResolveBinaryTradesRoute
  '/api/public/payhero/callback': typeof ApiPublicPayheroCallbackRoute
  '/api/public/payhero/withdraw-callback': typeof ApiPublicPayheroWithdrawCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/profile'
    | '/referrals'
    | '/support'
    | '/withdrawals'
    | '/api/public/hooks/resolve-binary-trades'
    | '/api/public/payhero/callback'
    | '/api/public/payhero/withdraw-callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/profile'
    | '/referrals'
    | '/support'
    | '/withdrawals'
    | '/api/public/hooks/resolve-binary-trades'
    | '/api/public/payhero/callback'
    | '/api/public/payhero/withdraw-callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/referrals'
    | '/_authenticated/support'
    | '/_authenticated/withdrawals'
    | '/api/public/hooks/resolve-binary-trades'
    | '/api/public/payhero/callback'
    | '/api/public/payhero/withdraw-callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksResolveBinaryTradesRoute: typeof ApiPublicHooksResolveBinaryTradesRoute
  ApiPublicPayheroCallbackRoute: typeof ApiPublicPayheroCallbackRoute
  ApiPublicPayheroWithdrawCallbackRoute: typeof ApiPublicPayheroWithdrawCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/withdrawals': {
      id: '/_authenticated/withdrawals'
      path: '/withdrawals'
      fullPath: '/withdrawals'
      preLoaderRoute: typeof AuthenticatedWithdrawalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/referrals': {
      id: '/_authenticated/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AuthenticatedReferralsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/payhero/withdraw-callback': {
      id: '/api/public/payhero/withdraw-callback'
      path: '/api/public/payhero/withdraw-callback'
      fullPath: '/api/public/payhero/withdraw-callback'
      preLoaderRoute: typeof ApiPublicPayheroWithdrawCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payhero/callback': {
      id: '/api/public/payhero/callback'
      path: '/api/public/payhero/callback'
      fullPath: '/api/public/payhero/callback'
      preLoaderRoute: typeof ApiPublicPayheroCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/resolve-binary-trades': {
      id: '/api/public/hooks/resolve-binary-trades'
      path: '/api/public/hooks/resolve-binary-trades'
      fullPath: '/api/public/hooks/resolve-binary-trades'
      preLoaderRoute: typeof ApiPublicHooksResolveBinaryTradesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReferralsRoute: typeof AuthenticatedReferralsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedWithdrawalsRoute: typeof AuthenticatedWithdrawalsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReferralsRoute: AuthenticatedReferralsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedWithdrawalsRoute: AuthenticatedWithdrawalsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksResolveBinaryTradesRoute:
    ApiPublicHooksResolveBinaryTradesRoute,
  ApiPublicPayheroCallbackRoute: ApiPublicPayheroCallbackRoute,
  ApiPublicPayheroWithdrawCallbackRoute: ApiPublicPayheroWithdrawCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
